server:
  port: 8999
spring:
  application:
    name: webmap
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
file:
  temp: D:\temp
  img: D:\temp
#  temp: /usr/temp
#  img: /usr/img
url:
  image-url: http://106.52.184.39/img/
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
