spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.52.184.39:3306/webmap?characterEncoding=utf8
    username: db_test
    password: Dxw123456
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      dxw:
        mapper: debug
